In [1]:
import random
from collections import Counter
from collections import defaultdict

In [2]:
import textwrap
import pandas as pd

In [3]:
africa_galore = pd.read_json(
    "https://storage.googleapis.com/dm-educational/assets/ai_foundations/africa_galore.json"
)

In [4]:
africa_galore.columns

Index(['category', 'name', 'description'], dtype='str')

In [5]:
africa_galore.head()

  category      name                                        description
0    Music  Afrobeat  The Lagos air was thick with humidity, but the...
1    Music  Highlife  The warm evening air in Accra was filled with ...
2    Music      Juju  The bustling streets of Lagos were alive with ...
3    Music    Mbalax  The Dakar waterfront was buzzing with activity...
4    Music   Soukous  The Kinshasa night was alive with the infectio...

In [6]:
dataset = africa_galore.get("description")

In [7]:
dataset.shape

(232,)

In [8]:
dataset[:10]

0    The Lagos air was thick with humidity, but the...
1    The warm evening air in Accra was filled with ...
2    The bustling streets of Lagos were alive with ...
3    The Dakar waterfront was buzzing with activity...
4    The Kinshasa night was alive with the infectio...
5    In a small township outside Durban, a group of...
6    The vibrant colors and intricate patterns of K...
7    Bogolanfini, or mud cloth, from Mali, is a tex...
8    Adire, a resist-dyed indigo cloth from Nigeria...
9    Kanga, a colorful printed cloth from East Afri...
Name: description, dtype: str

In [9]:
def space_tokenize(text: str) -> list[str]:
    tokens = text.split(" ")
    return tokens

In [10]:
space_tokenize("My name is Srushanth Baride")

['My', 'name', 'is', 'Srushanth', 'Baride']

In [11]:
tokens = space_tokenize(dataset[0])

In [12]:
len(tokens)

118

In [13]:
len(set(tokens))

83

In [14]:
tokens

['The',
 'Lagos',
 'air',
 'was',
 'thick',
 'with',
 'humidity,',
 'but',
 'the',
 'energy',
 'in',
 'the',
 'club',
 'was',
 'electric.',
 'The',
 'band',
 'launched',
 'into',
 'a',
 'hypnotic',
 'Afrobeat',
 'groove,',
 'the',
 'drums',
 'pounding',
 'out',
 'a',
 'complex',
 'polyrhythm,',
 'the',
 'horns',
 'blaring',
 'a',
 'soaring',
 'melody,',
 'and',
 'the',
 'bass',
 'laying',
 'down',
 'a',
 'deep,',
 'funky',
 'foundation.',
 'A',
 'woman',
 'named',
 'Imani',
 'moved',
 'effortlessly',
 'to',
 'the',
 'music,',
 'her',
 'body',
 'swaying',
 'in',
 'time',
 'with',
 'the',
 'rhythm.',
 'The',
 'music',
 'seemed',
 'to',
 'flow',
 'through',
 'her,',
 'a',
 'powerful',
 'current',
 'of',
 'energy',
 'and',
 'joy.',
 'All',
 'around',
 'her,',
 'people',
 'were',
 'dancing,',
 'singing,',
 'and',
 'clapping,',
 'caught',
 'up',
 'in',
 'the',
 'infectious',
 'rhythm.',
 'The',
 'music',
 'was',
 'more',
 'than',
 'just',
 'entertainment;',
 'it',
 'was',
 'a',
 'celebration',
 'of',
 'life,',
 'a',
 'connection',
 'to',
 'their',
 'shared',
 'heritage,',
 'a',
 'vibrant',
 'expression',
 'of',
 'the',
 'soul',
 'of',
 'Lagos.']

In [15]:
n = 3
ngrams = []
for i in range(0, len(tokens)-n+1):
    print(tokens[i:i+n])
    print(tuple(tokens[i:i+n]))
    ngrams.append(tuple(tokens[i:i+n]))

['The', 'Lagos', 'air']
('The', 'Lagos', 'air')
['Lagos', 'air', 'was']
('Lagos', 'air', 'was')
['air', 'was', 'thick']
('air', 'was', 'thick')
['was', 'thick', 'with']
('was', 'thick', 'with')
['thick', 'with', 'humidity,']
('thick', 'with', 'humidity,')
['with', 'humidity,', 'but']
('with', 'humidity,', 'but')
['humidity,', 'but', 'the']
('humidity,', 'but', 'the')
['but', 'the', 'energy']
('but', 'the', 'energy')
['the', 'energy', 'in']
('the', 'energy', 'in')
['energy', 'in', 'the']
('energy', 'in', 'the')
['in', 'the', 'club']
('in', 'the', 'club')
['the', 'club', 'was']
('the', 'club', 'was')
['club', 'was', 'electric.']
('club', 'was', 'electric.')
['was', 'electric.', 'The']
('was', 'electric.', 'The')
['electric.', 'The', 'band']
('electric.', 'The', 'band')
['The', 'band', 'launched']
('The', 'band', 'launched')
['band', 'launched', 'into']
('band', 'launched', 'into')
['launched', 'into', 'a']
('launched', 'into', 'a')
['into', 'a', 'hypnotic']
('into', 'a', 'hypnotic')
['a', 'hypnotic', 'Afrobeat']
('a', 'hypnotic', 'Afrobeat')
['hypnotic', 'Afrobeat', 'groove,']
('hypnotic', 'Afrobeat', 'groove,')
['Afrobeat', 'groove,', 'the']
('Afrobeat', 'groove,', 'the')
['groove,', 'the', 'drums']
('groove,', 'the', 'drums')
['the', 'drums', 'pounding']
('the', 'drums', 'pounding')
['drums', 'pounding', 'out']
('drums', 'pounding', 'out')
['pounding', 'out', 'a']
('pounding', 'out', 'a')
['out', 'a', 'complex']
('out', 'a', 'complex')
['a', 'complex', 'polyrhythm,']
('a', 'complex', 'polyrhythm,')
['complex', 'polyrhythm,', 'the']
('complex', 'polyrhythm,', 'the')
['polyrhythm,', 'the', 'horns']
('polyrhythm,', 'the', 'horns')
['the', 'horns', 'blaring']
('the', 'horns', 'blaring')
['horns', 'blaring', 'a']
('horns', 'blaring', 'a')
['blaring', 'a', 'soaring']
('blaring', 'a', 'soaring')
['a', 'soaring', 'melody,']
('a', 'soaring', 'melody,')
['soaring', 'melody,', 'and']
('soaring', 'melody,', 'and')
['melody,', 'and', 'the']
('melody,', 'and', 'the')
['and', 'the', 'bass']
('and', 'the', 'bass')
['the', 'bass', 'laying']
('the', 'bass', 'laying')
['bass', 'laying', 'down']
('bass', 'laying', 'down')
['laying', 'down', 'a']
('laying', 'down', 'a')
['down', 'a', 'deep,']
('down', 'a', 'deep,')
['a', 'deep,', 'funky']
('a', 'deep,', 'funky')
['deep,', 'funky', 'foundation.']
('deep,', 'funky', 'foundation.')
['funky', 'foundation.', 'A']
('funky', 'foundation.', 'A')
['foundation.', 'A', 'woman']
('foundation.', 'A', 'woman')
['A', 'woman', 'named']
('A', 'woman', 'named')
['woman', 'named', 'Imani']
('woman', 'named', 'Imani')
['named', 'Imani', 'moved']
('named', 'Imani', 'moved')
['Imani', 'moved', 'effortlessly']
('Imani', 'moved', 'effortlessly')
['moved', 'effortlessly', 'to']
('moved', 'effortlessly', 'to')
['effortlessly', 'to', 'the']
('effortlessly', 'to', 'the')
['to', 'the', 'music,']
('to', 'the', 'music,')
['the', 'music,', 'her']
('the', 'music,', 'her')
['music,', 'her', 'body']
('music,', 'her', 'body')
['her', 'body', 'swaying']
('her', 'body', 'swaying')
['body', 'swaying', 'in']
('body', 'swaying', 'in')
['swaying', 'in', 'time']
('swaying', 'in', 'time')
['in', 'time', 'with']
('in', 'time', 'with')
['time', 'with', 'the']
('time', 'with', 'the')
['with', 'the', 'rhythm.']
('with', 'the', 'rhythm.')
['the', 'rhythm.', 'The']
('the', 'rhythm.', 'The')
['rhythm.', 'The', 'music']
('rhythm.', 'The', 'music')
['The', 'music', 'seemed']
('The', 'music', 'seemed')
['music', 'seemed', 'to']
('music', 'seemed', 'to')
['seemed', 'to', 'flow']
('seemed', 'to', 'flow')
['to', 'flow', 'through']
('to', 'flow', 'through')
['flow', 'through', 'her,']
('flow', 'through', 'her,')
['through', 'her,', 'a']
('through', 'her,', 'a')
['her,', 'a', 'powerful']
('her,', 'a', 'powerful')
['a', 'powerful', 'current']
('a', 'powerful', 'current')
['powerful', 'current', 'of']
('powerful', 'current', 'of')
['current', 'of', 'energy']
('current', 'of', 'energy')
['of', 'energy', 'and']
('of', 'energy', 'and')
['energy', 'and', 'joy.']
('energy', 'and', 'joy.')
['and', 'joy.', 'All']
('and', 'joy.', 'All')
['joy.', 'All', 'around']
('joy.', 'All', 'around')
['All', 'around', 'her,']
('All', 'around', 'her,')
['around', 'her,', 'people']
('around', 'her,', 'people')
['her,', 'people', 'were']
('her,', 'people', 'were')
['people', 'were', 'dancing,']
('people', 'were', 'dancing,')
['were', 'dancing,', 'singing,']
('were', 'dancing,', 'singing,')
['dancing,', 'singing,', 'and']
('dancing,', 'singing,', 'and')
['singing,', 'and', 'clapping,']
('singing,', 'and', 'clapping,')
['and', 'clapping,', 'caught']
('and', 'clapping,', 'caught')
['clapping,', 'caught', 'up']
('clapping,', 'caught', 'up')
['caught', 'up', 'in']
('caught', 'up', 'in')
['up', 'in', 'the']
('up', 'in', 'the')
['in', 'the', 'infectious']
('in', 'the', 'infectious')
['the', 'infectious', 'rhythm.']
('the', 'infectious', 'rhythm.')
['infectious', 'rhythm.', 'The']
('infectious', 'rhythm.', 'The')
['rhythm.', 'The', 'music']
('rhythm.', 'The', 'music')
['The', 'music', 'was']
('The', 'music', 'was')
['music', 'was', 'more']
('music', 'was', 'more')
['was', 'more', 'than']
('was', 'more', 'than')
['more', 'than', 'just']
('more', 'than', 'just')
['than', 'just', 'entertainment;']
('than', 'just', 'entertainment;')
['just', 'entertainment;', 'it']
('just', 'entertainment;', 'it')
['entertainment;', 'it', 'was']
('entertainment;', 'it', 'was')
['it', 'was', 'a']
('it', 'was', 'a')
['was', 'a', 'celebration']
('was', 'a', 'celebration')
['a', 'celebration', 'of']
('a', 'celebration', 'of')
['celebration', 'of', 'life,']
('celebration', 'of', 'life,')
['of', 'life,', 'a']
('of', 'life,', 'a')
['life,', 'a', 'connection']
('life,', 'a', 'connection')
['a', 'connection', 'to']
('a', 'connection', 'to')
['connection', 'to', 'their']
('connection', 'to', 'their')
['to', 'their', 'shared']
('to', 'their', 'shared')
['their', 'shared', 'heritage,']
('their', 'shared', 'heritage,')
['shared', 'heritage,', 'a']
('shared', 'heritage,', 'a')
['heritage,', 'a', 'vibrant']
('heritage,', 'a', 'vibrant')
['a', 'vibrant', 'expression']
('a', 'vibrant', 'expression')
['vibrant', 'expression', 'of']
('vibrant', 'expression', 'of')
['expression', 'of', 'the']
('expression', 'of', 'the')
['of', 'the', 'soul']
('of', 'the', 'soul')
['the', 'soul', 'of']
('the', 'soul', 'of')
['soul', 'of', 'Lagos.']
('soul', 'of', 'Lagos.')

In [16]:
ngrams

[('The', 'Lagos', 'air'),
 ('Lagos', 'air', 'was'),
 ('air', 'was', 'thick'),
 ('was', 'thick', 'with'),
 ('thick', 'with', 'humidity,'),
 ('with', 'humidity,', 'but'),
 ('humidity,', 'but', 'the'),
 ('but', 'the', 'energy'),
 ('the', 'energy', 'in'),
 ('energy', 'in', 'the'),
 ('in', 'the', 'club'),
 ('the', 'club', 'was'),
 ('club', 'was', 'electric.'),
 ('was', 'electric.', 'The'),
 ('electric.', 'The', 'band'),
 ('The', 'band', 'launched'),
 ('band', 'launched', 'into'),
 ('launched', 'into', 'a'),
 ('into', 'a', 'hypnotic'),
 ('a', 'hypnotic', 'Afrobeat'),
 ('hypnotic', 'Afrobeat', 'groove,'),
 ('Afrobeat', 'groove,', 'the'),
 ('groove,', 'the', 'drums'),
 ('the', 'drums', 'pounding'),
 ('drums', 'pounding', 'out'),
 ('pounding', 'out', 'a'),
 ('out', 'a', 'complex'),
 ('a', 'complex', 'polyrhythm,'),
 ('complex', 'polyrhythm,', 'the'),
 ('polyrhythm,', 'the', 'horns'),
 ('the', 'horns', 'blaring'),
 ('horns', 'blaring', 'a'),
 ('blaring', 'a', 'soaring'),
 ('a', 'soaring', 'melody,'),
 ('soaring', 'melody,', 'and'),
 ('melody,', 'and', 'the'),
 ('and', 'the', 'bass'),
 ('the', 'bass', 'laying'),
 ('bass', 'laying', 'down'),
 ('laying', 'down', 'a'),
 ('down', 'a', 'deep,'),
 ('a', 'deep,', 'funky'),
 ('deep,', 'funky', 'foundation.'),
 ('funky', 'foundation.', 'A'),
 ('foundation.', 'A', 'woman'),
 ('A', 'woman', 'named'),
 ('woman', 'named', 'Imani'),
 ('named', 'Imani', 'moved'),
 ('Imani', 'moved', 'effortlessly'),
 ('moved', 'effortlessly', 'to'),
 ('effortlessly', 'to', 'the'),
 ('to', 'the', 'music,'),
 ('the', 'music,', 'her'),
 ('music,', 'her', 'body'),
 ('her', 'body', 'swaying'),
 ('body', 'swaying', 'in'),
 ('swaying', 'in', 'time'),
 ('in', 'time', 'with'),
 ('time', 'with', 'the'),
 ('with', 'the', 'rhythm.'),
 ('the', 'rhythm.', 'The'),
 ('rhythm.', 'The', 'music'),
 ('The', 'music', 'seemed'),
 ('music', 'seemed', 'to'),
 ('seemed', 'to', 'flow'),
 ('to', 'flow', 'through'),
 ('flow', 'through', 'her,'),
 ('through', 'her,', 'a'),
 ('her,', 'a', 'powerful'),
 ('a', 'powerful', 'current'),
 ('powerful', 'current', 'of'),
 ('current', 'of', 'energy'),
 ('of', 'energy', 'and'),
 ('energy', 'and', 'joy.'),
 ('and', 'joy.', 'All'),
 ('joy.', 'All', 'around'),
 ('All', 'around', 'her,'),
 ('around', 'her,', 'people'),
 ('her,', 'people', 'were'),
 ('people', 'were', 'dancing,'),
 ('were', 'dancing,', 'singing,'),
 ('dancing,', 'singing,', 'and'),
 ('singing,', 'and', 'clapping,'),
 ('and', 'clapping,', 'caught'),
 ('clapping,', 'caught', 'up'),
 ('caught', 'up', 'in'),
 ('up', 'in', 'the'),
 ('in', 'the', 'infectious'),
 ('the', 'infectious', 'rhythm.'),
 ('infectious', 'rhythm.', 'The'),
 ('rhythm.', 'The', 'music'),
 ('The', 'music', 'was'),
 ('music', 'was', 'more'),
 ('was', 'more', 'than'),
 ('more', 'than', 'just'),
 ('than', 'just', 'entertainment;'),
 ('just', 'entertainment;', 'it'),
 ('entertainment;', 'it', 'was'),
 ('it', 'was', 'a'),
 ('was', 'a', 'celebration'),
 ('a', 'celebration', 'of'),
 ('celebration', 'of', 'life,'),
 ('of', 'life,', 'a'),
 ('life,', 'a', 'connection'),
 ('a', 'connection', 'to'),
 ('connection', 'to', 'their'),
 ('to', 'their', 'shared'),
 ('their', 'shared', 'heritage,'),
 ('shared', 'heritage,', 'a'),
 ('heritage,', 'a', 'vibrant'),
 ('a', 'vibrant', 'expression'),
 ('vibrant', 'expression', 'of'),
 ('expression', 'of', 'the'),
 ('of', 'the', 'soul'),
 ('the', 'soul', 'of'),
 ('soul', 'of', 'Lagos.')]

In [17]:
all_unigrams = []
all_bigrams = []
all_trigrams = []

In [18]:
def generate_ngrams(text: str, n: int) -> list[tuple[str]]:
    tokens = space_tokenize(text=text)
    ngrams = []
    for i in range(0, len(tokens)-n+1):
        ngrams.append(tuple(tokens[i:i+n]))
    return ngrams

In [19]:
for paragraph in dataset:
    # Calling `generate_ngrams` with n=1 constructs a list of unigrams.
    all_unigrams.extend(generate_ngrams(paragraph, n=1))
    # Calling `generate_ngrams` with n=2 constructs a list of bigrams (2-grams).
    all_bigrams.extend(generate_ngrams(paragraph, n=2))
    # Calling `generate_ngrams` with n=2 constructs a list of trigram (3-grams).
    all_trigrams.extend(generate_ngrams(paragraph, n=3))

In [20]:
print("First 10 Unigrams:", all_unigrams[:10])
print("First 10 Bigrams:", all_bigrams[:10])
print("First 10 Trigrams:", all_trigrams[:10])

First 10 Unigrams: [('The',), ('Lagos',), ('air',), ('was',), ('thick',), ('with',), ('humidity,',), ('but',), ('the',), ('energy',)]
First 10 Bigrams: [('The', 'Lagos'), ('Lagos', 'air'), ('air', 'was'), ('was', 'thick'), ('thick', 'with'), ('with', 'humidity,'), ('humidity,', 'but'), ('but', 'the'), ('the', 'energy'), ('energy', 'in')]
First 10 Trigrams: [('The', 'Lagos', 'air'), ('Lagos', 'air', 'was'), ('air', 'was', 'thick'), ('was', 'thick', 'with'), ('thick', 'with', 'humidity,'), ('with', 'humidity,', 'but'), ('humidity,', 'but', 'the'), ('but', 'the', 'energy'), ('the', 'energy', 'in'), ('energy', 'in', 'the')]

In [26]:
bigram_counts = Counter(all_bigrams)
bigram_counts

Counter({('is', 'a'): 144,
         ('of', 'the'): 100,
         ('and', 'the'): 69,
         ('in', 'the'): 61,
         ('with', 'a'): 60,
         ('in', 'a'): 55,
         ('and', 'a'): 50,
         ('to', 'the'): 42,
         ('was', 'a'): 39,
         ('It', 'is'): 33,
         ('went', 'looking'): 32,
         ('looking', 'for'): 32,
         ('with', 'the'): 31,
         ('for', 'a'): 31,
         ('as', 'a'): 30,
         ('made', 'from'): 29,
         ('on', 'the'): 25,
         ('from', 'the'): 24,
         ('such', 'as'): 23,
         ('for', 'its'): 23,
         ('by', 'the'): 23,
         ('served', 'with'): 23,
         ('symbol', 'of'): 22,
         ('for', 'the'): 22,
         ('a', 'traditional'): 20,
         ('can', 'be'): 20,
         ('it', 'a'): 19,
         ('has', 'a'): 19,
         ('is', 'the'): 19,
         ('at', 'a'): 18,
         ('a', 'symbol'): 18,
         ('was', 'hungry'): 18,
         ('hungry', 'so'): 18,
         ('The', 'result'): 17,
         ('result', 'is'): 17,
         ('a', 'small'): 16,
         ('on', 'a'): 16,
         ('she', 'went'): 16,
         ('he', 'went'): 16,
         ('more', 'than'): 15,
         ('filled', 'with'): 15,
         ('is', 'made'): 15,
         ('it', 'was'): 14,
         ('characterized', 'by'): 14,
         ('a', 'popular'): 14,
         ('one', 'of'): 14,
         ('aroma', 'of'): 14,
         ('is', 'often'): 14,
         ('often', 'served'): 14,
         ('so', 'he'): 14,
         ('so', 'she'): 14,
         ('and', 'is'): 14,
         ('into', 'a'): 13,
         ('than', 'just'): 13,
         ('a', 'vibrant'): 13,
         ('as', 'the'): 13,
         ('South', 'African'): 13,
         ('a', 'staple'): 13,
         ('made', 'with'): 13,
         ('to', 'a'): 12,
         ('through', 'the'): 12,
         ('parts', 'of'): 12,
         ('made', 'by'): 12,
         ('was', 'more'): 11,
         ('blend', 'of'): 11,
         ('way', 'to'): 11,
         ('a', 'testament'): 11,
         ('testament', 'to'): 11,
         ('by', 'a'): 11,
         ('it', 'is'): 11,
         ('a', 'taste'): 11,
         ('taste', 'of'): 11,
         ('a', 'rich'): 11,
         ('of', 'a'): 11,
         ('West', 'African'): 11,
         ('the', 'rich'): 10,
         ('by', 'its'): 10,
         ('reflecting', 'the'): 10,
         ('a', 'unique'): 10,
         ('making', 'it'): 10,
         ('The', 'air'): 10,
         ('into', 'the'): 10,
         ('creating', 'a'): 10,
         ('scent', 'of'): 10,
         ('a', 'hearty'): 10,
         ('was', 'thirsty'): 10,
         ('thirsty', 'so'): 10,
         ('and', 'sometimes'): 10,
         ('popular', 'in'): 10,
         ('air', 'was'): 9,
         ('and', 'other'): 9,
         ('known', 'as'): 9,
         ('the', 'air'): 9,
         ('the', 'African'): 9,
         ('seasoned', 'with'): 9,
         ('sweet', 'and'): 9,
         ('renowned', 'for'): 9,
         ('a', 'place'): 9,
         ('and', 'often'): 9,
         ('refreshing', 'and'): 9,
         ('with', 'spices'): 9,
         ('reminder', 'of'): 8,
         ('and', 'its'): 8,
         ('throughout', 'the'): 8,
         ('create', 'a'): 8,
         ('known', 'for'): 8,
         ('in', 'their'): 8,
         ('like', 'the'): 8,
         ('flavor', 'and'): 8,
         ('pieces', 'of'): 8,
         ('a', 'spicy'): 8,
         ('UNESCO', 'World'): 8,
         ('World', 'Heritage'): 8,
         ('a', 'refreshing'): 8,
         ('is', 'typically'): 8,
         ('that', 'is'): 8,
         ('often', 'enjoyed'): 8,
         ('served', 'in'): 8,
         ('of', 'his'): 7,
         ('over', 'the'): 7,
         ('filled', 'the'): 7,
         ('and', 'cultural'): 7,
         ('for', 'their'): 7,
         ('As', 'the'): 7,
         ('burst', 'of'): 7,
         ('to', 'be'): 7,
         ('and', 'vegetables'): 7,
         ('to', 'create'): 7,
         ('a', 'bustling'): 7,
         ('and', 'their'): 7,
         ('dish', 'made'): 7,
         ('staple', 'in'): 7,
         ('leaves', 'and'): 7,
         ('and', 'most'): 7,
         ('offering', 'a'): 7,
         ('are', 'a'): 7,
         ('the', 'most'): 7,
         ('a', 'vital'): 7,
         ('a', 'simple'): 7,
         ('language', 'family'): 7,
         ('the', 'largest'): 7,
         ('languages', 'are'): 7,
         ('typically', 'served'): 7,
         ('is', 'usually'): 7,
         ('and', 'served'): 7,
         ('similar', 'to'): 7,
         ('mixed', 'with'): 7,
         ('countries', 'like'): 7,
         ('a', 'side'): 6,
         ('a', 'reminder'): 6,
         ('a', 'woman'): 6,
         ('a', 'warm'): 6,
         ('the', 'vibrant'): 6,
         ('power', 'of'): 6,
         ('just', 'a'): 6,
         ('East', 'African'): 6,
         ('the', 'power'): 6,
         ('of', 'African'): 6,
         ('is', 'characterized'): 6,
         ('in', 'this'): 6,
         ('a', 'variety'): 6,
         ('variety', 'of'): 6,
         ('is', 'also'): 6,
         ('resulting', 'in'): 6,
         ('in', 'many'): 6,
         ('of', 'Africa,'): 6,
         ('lived', 'in'): 6,
         ('of', 'her'): 6,
         ('and', 'slightly'): 6,
         ('a', 'large,'): 6,
         ('to', 'scoop'): 6,
         ('scoop', 'up'): 6,
         ('up', 'the'): 6,
         ('garlic,', 'and'): 6,
         ('at', 'the'): 6,
         ('the', 'flavorful'): 6,
         ('-', 'the'): 6,
         ('a', 'smooth,'): 6,
         ('of', 'their'): 6,
         ('at', 'its'): 6,
         ('water', 'and'): 6,
         ('a', 'comforting'): 6,
         ('onions,', 'and'): 6,
         ('a', 'street'): 6,
         ('It', 'was'): 6,
         ('provided', 'a'): 6,
         ('of', "Africa's"): 6,
         ('the', "world's"): 6,
         ('a', 'UNESCO'): 6,
         ('role', 'in'): 6,
         ('place', 'where'): 6,
         ('tea', 'and'): 6,
         ('is', 'one'): 6,
         ('used', 'in'): 6,
         ('glass', 'of'): 6,
         ('be', 'a'): 6,
         ('or', 'a'): 6,
         ('cup', 'of'): 6,
         ('cooked', 'in'): 6,
         ('giving', 'it'): 6,
         ('It', 'has'): 6,
         ('a', 'savory'): 6,
         ('cooked', 'with'): 6,
         ('spices', 'such'): 6,
         ('leaves', 'are'): 6,
         ('energy', 'and'): 5,
         ('life,', 'a'): 5,
         ('under', 'the'): 5,
         ('group', 'of'): 5,
         ('In', 'a'): 5,
         ('of', 'life'): 5,
         ('of', 'Africa.'): 5,
         ('East', 'Africa,'): 5,
         ('also', 'known'): 5,
         ('a', 'wide'): 5,
         ('range', 'of'): 5,
         ('in', 'Southern'): 5,
         ('along', 'with'): 5,
         ('to', 'its'): 5,
         ('the', 'surrounding'): 5,
         ('coast', 'is'): 5,
         ('fruits,', 'vegetables,'): 5,
         ('due', 'to'): 5,
         ('part', 'of'): 5,
         ('the', 'rhythmic'): 5,
         ('understanding', 'of'): 5,
         ('fried', 'plantains'): 5,
         ('a', 'burst'): 5,
         ('just', 'food;'): 5,
         ('food;', 'it'): 5,
         ('of', 'home,'): 5,
         ('where', 'the'): 5,
         ('slightly', 'sour'): 5,
         ('-', 'a'): 5,
         ('a', 'slightly'): 5,
         ('it', 'to'): 5,
         ('array', 'of'): 5,
         ('with', 'onions,'): 5,
         ('spices,', 'and'): 5,
         ('across', 'the'): 5,
         ('outside', 'and'): 5,
         ('a', 'dish'): 5,
         ('its', 'unique'): 5,
         ('a', 'large'): 5,
         ('a', 'mixture'): 5,
         ('street', 'food'): 5,
         ('from', 'fermented'): 5,
         ('the', 'day'): 5,
         ('meat', 'and'): 5,
         ('from', 'South'): 5,
         ('a', 'vast'): 5,
         ('the', 'scent'): 5,
         ('from', 'a'): 5,
         ('family', 'is'): 5,
         ('in', 'Africa'): 5,
         ('are', 'often'): 5,
         ('they', 'are'): 5,
         ('sculpture,', 'from'): 5,
         ('health', 'and'): 5,
         ('crucial', 'for'): 5,
         ('a', 'hot'): 5,
         ('him', 'to'): 5,
         ('tomato', 'and'): 5,
         ('color', 'and'): 5,
         ('served', 'at'): 5,
         ('soup', 'is'): 5,
         ('texture', 'and'): 5,
         ('Africa,', 'especially'): 5,
         ('Africa.', 'It'): 5,
         ('used', 'to'): 5,
         ('dish', 'of'): 5,
         ('bowl', 'of'): 5,
         ('a', 'plate'): 5,
         ('plate', 'of'): 5,
         ('paired', 'with'): 5,
         ('green', 'tea'): 5,
         ('dish', 'in'): 5,
         ('eaten', 'with'): 5,
         ('spices', 'like'): 5,
         ('in', 'East'): 5,
         ('with', 'water'): 5,
         ('usually', 'served'): 5,
         ('is', 'used'): 5,
         ('which', 'is'): 5,
         ('a', 'sweet'): 5,
         ('a', 'complex'): 4,
         ('The', 'music'): 4,
         ('a', 'powerful'): 4,
         ('a', 'celebration'): 4,
         ('celebration', 'of'): 4,
         ('to', 'their'): 4,
         ('heritage,', 'a'): 4,
         ('expression', 'of'): 4,
         ('was', 'filled'): 4,
         ('At', 'a'): 4,
         ('a', 'source'): 4,
         ('source', 'of'): 4,
         ('the', 'bustling'): 4,
         ('alive', 'with'): 4,
         ('sounds', 'of'): 4,
         ('the', 'distinctive'): 4,
         ('woman', 'with'): 4,
         ('rich', 'cultural'): 4,
         ('the', 'heart'): 4,
         ('heart', 'of'): 4,
         ('of', 'an'): 4,
         ('vibrant', 'colors'): 4,
         ('stories', 'of'): 4,
         ('and', 'social'): 4,
         ('rich', 'and'): 4,
         ('of', 'Yoruba'): 4,
         ('passed', 'down'): 4,
         ('Africa,', 'particularly'): 4,
         ('serving', 'as'): 4,
         ('of', 'East'): 4,
         ('Africa', 'and'): 4,
         ('a', 'beloved'): 4,
         ('Southern', 'Africa,'): 4,
         ('South', 'Africa.'): 4,
         ('cultural', 'heritage'): 4,
         ('climate,', 'with'): 4,
         ('during', 'the'): 4,
         ('a', 'few'): 4,
         ('by', 'their'): 4,
         ('are', 'known'): 4,
         ('plant', 'and'): 4,
         ('and', 'animal'): 4,
         ('coast', 'of'): 4,
         ('on', 'Earth.'): 4,
         ('the', 'warm'): 4,
         ('girl', 'with'): 4,
         ('vibrant', 'red'): 4,
         ('of', 'flavor'): 4,
         ('When', 'the'): 4,
         ('garnished', 'with'): 4,
         ('high', 'in'): 4,
         ('the', 'Ethiopian'): 4,
         ('called', 'a'): 4,
         ('would', 'carefully'): 4,
         ('tear', 'off'): 4,
         ('land', 'and'): 4,
         ('a', 'low'): 4,
         ('As', 'they'): 4,
         ('While', 'the'): 4,
         ('long', 'shadows'): 4,
         ('the', 'outside'): 4,
         ('shared', 'stories'): 4,
         ('dish', 'that'): 4,
         ('the', 'aroma'): 4,
         ('juice,', 'and'): 4,
         ('mixture', 'of'): 4,
         ('the', 'savory'): 4,
         ('sauce', 'and'): 4,
         ('the', 'city'): 4,
         ('portion', 'of'): 4,
         ('rhythmic', 'beat'): 4,
         ('beat', 'of'): 4,
         ('with', 'grilled'): 4,
         ('amidst', 'the'): 4,
         ('after', 'a'): 4,
         ('a', 'rich,'): 4,
         ('stories', 'and'): 4,
         ('In', 'the'): 4,
         ('around', 'a'): 4,
         ('and', 'spices.'): 4,
         ('and', 'satisfying'): 4,
         ('of', 'meat'): 4,
         ('a', 'nutritious'): 4,
         ('eager', 'to'): 4,
         ('is', 'an'): 4,
         ('largest', 'and'): 4,
         ('over', 'a'): 4,
         ('the', 'Great'): 4,
         ('beliefs', 'of'): 4,
         ('Heritage', 'Site'): 4,
         ('South', 'Africa,'): 4,
         ('National', 'Park,'): 4,
         ('located', 'in'): 4,
         ('The', "park's"): 4,
         ('The', 'park'): 4,
         ('vital', 'role'): 4,
         ('the', 'small'): 4,
         ('the', 'enticing'): 4,
         ('West', 'Africa,'): 4,
         ('the', 'world.'): 4,
         ('and', 'parts'): 4,
         ('spoken', 'in'): 4,
         ('They', 'are'): 4,
         ('and', 'well-being.'): 4,
         ('and', 'nutritious'): 4,
         ('a', 'strong'): 4,
         ('a', 'healthy'): 4,
         ('rich', 'in'): 4,
         ('essential', 'for'): 4,
         ('water', 'is'): 4,
         ('especially', 'in'): 4,
         ('to', 'quench'): 4,
         ('slightly', 'sweet'): 4,
         ('a', 'thick'): 4,
         ('a', 'flavorful'): 4,
         ('taste.', 'It'): 4,
         ('beef', 'or'): 4,
         ('marinated', 'in'): 4,
         ('made', 'of'): 4,
         ('of', 'ground'): 4,
         ('chicken', 'is'): 4,
         ('Often', 'served'): 4,
         ('drawn', 'by'): 4,
         ('and', 'spices'): 4,
         ('accompanied', 'by'): 4,
         ('a', 'local'): 4,
         ('a', 'cup'): 4,
         ('traditional', 'South'): 4,
         ('street', 'vendor'): 4,
         ('with', 'ginger'): 4,
         ('slightly', 'tangy'): 4,
         ('a', 'long'): 4,
         ('is', 'cooked'): 4,
         ('(such', 'as'): 4,
         ('a', 'creamy'): 4,
         ('The', 'stew'): 4,
         ('stew', 'is'): 4,
         ('dish', 'often'): 4,
         ('enjoyed', 'as'): 4,
         ('enjoyed', 'with'): 4,
         ('fried', 'dough'): 4,
         ('and', 'Tanzania.'): 4,
         ('is', 'enjoyed'): 4,
         ('and', 'it'): 4,
         ('for', 'extra'): 4,
         ('spiced', 'with'): 4,
         ('is', 'commonly'): 4,
         ('cassava', 'leaves'): 4,
         ('Central', 'African'): 4,
         ('flavored', 'with'): 4,
         ('a', 'thick,'): 4,
         ('Southern', 'Africa.'): 4,
         ('enjoyed', 'at'): 4,
         ('plain', 'or'): 4,
         ('drink', 'made'): 4,
         ('drink', 'is'): 4,
         ('tea', 'is'): 4,
         ('square', 'kilometers'): 4,
         ('sq', 'mi)'): 4,
         ('herds', 'of'): 4,
         ('Park', 'is'): 4,
         ('including', 'the'): 4,
         ('thick', 'with'): 3,
         ('the', 'energy'): 3,
         ('of', 'energy'): 3,
         ('music', 'was'): 3,
         ('their', 'shared'): 3,
         ('vibrant', 'expression'): 3,
         ('adding', 'a'): 3,
         ('a', 'man'): 3,
         ('man', 'with'): 3,
         ('lost', 'in'): 3,
         ('music.', 'The'): 3,
         ('of', 'family'): 3,
         ('to', 'his'): 3,
         ('the', 'sounds'): 3,
         ('smile', 'and'): 3,
         ('in', 'her'): 3,
         ('the', 'sun'): 3,
         ('began', 'to'): 3,
         ('the', 'complex'): 3,
         ('their', 'faces'): 3,
         ('music', 'and'): 3,
         ('was', 'alive'): 3,
         ('a', 'group'): 3,
         ('They', 'were'): 3,
         ('with', 'their'): 3,
         ('The', 'vibrant'): 3,
         ('of', 'Ghanaian'): 3,
         ('geometric', 'designs,'): 3,
         ('and', 'ceremonies,'): 3,
         ('From', 'the'): 3,
         ('created', 'using'): 3,
         ('The', 'process'): 3,
         ('has', 'become'): 3,
         ('from', 'Nigeria,'): 3,
         ("it's", 'a'): 3,
         ('wide', 'range'): 3,
         ('and', 'South'): 3,
         ('unique', 'and'): 3,
         ('Rainfall', 'is'): 3,
         ('with', 'some'): 3,
         ('the', 'day,'): 3,
         ('contributing', 'to'): 3,
         ('year.', 'The'): 3,
         ('the', 'Sahara'): 3,
         ('a', 'hot,'): 3,
         ('a', 'distinct'): 3,
         ('distinct', 'wet'): 3,
         ('wet', 'and'): 3,
         ('and', 'dry'): 3,
         ('dry', 'season'): 3,
         ('living', 'in'): 3,
         ('temperate', 'climate,'): 3,
         ('combination', 'of'): 3,
         ('temperatures', 'and'): 3,
         ('of', 'North'): 3,
         ('summers', 'and'): 3,
         ('are', 'typically'): 3,
         ('with', 'warm'): 3,
         ('vegetables,', 'and'): 3,
         ('Southern', 'Africa'): 3,
         ('have', 'a'): 3,
         ('more', 'temperate'): 3,
         ('in', 'some'): 3,
         ('small', 'village'): 3,
         ('with', 'anticipation.'): 3,
         ('finely', 'chopped'): 3,
         ('the', 'air.'): 3,
         ('peppers,', 'and'): 3,
         ('a', 'secret'): 3,
         ('secret', 'blend'): 3,
         ('of', 'spices'): 3,
         ('down', 'through'): 3,
         ('with', 'each'): 3,
         ('she', 'would'): 3,
         ('the', 'Jollof'): 3,
         ('it', 'on'): 3,
         ('plantains', 'and'): 3,
         ('chicken.', 'The'): 3,
         ('the', 'fire'): 3,
         ('family,', 'and'): 3,
         ('a', 'boy'): 3,
         ('boy', 'with'): 3,
         ('Mama', 'Selamawit'): 3,
         ('that', 'gave'): 3,
         ('its', 'distinctive'): 3,
         ('fill', 'with'): 3,
         ('sour,', 'yeasty'): 3,
         ('comforting', 'and'): 3,
         ('to', 'tear'): 3,
         ('stews', 'and'): 3,
         ('Each', 'bite'): 3,
         ('a', 'symphony'): 3,
         ('symphony', 'of'): 3,
         ('a', 'girl'): 3,
         ('eyes', 'and'): 3,
         ('exploring', 'the'): 3,
         ('or', 'chicken'): 3,
         ('onions,', 'garlic,'): 3,
         ('fruits', 'like'): 3,
         ('the', 'tagine'): 3,
         ('of', 'Moroccan'): 3,
         ('infused', 'with'): 3,
         ('sun', 'beat'): 3,
         ('beat', 'down'): 3,
         ('the', 'dusty'): 3,
         ('Pap', 'en'): 3,
         ('a', 'South'): 3,
         ('and', 'juicy'): 3,
         ('a', 'hint'): 3,
         ('hint', 'of'): 3,
         ('the', 'meat'): 3,
         ('casting', 'long'): 3,
         ('the', 'smoky'): 3,
         ('a', 'mound'): 3,
         ('home,', 'a'): 3,
         ('the', 'afternoon'): 3,
         ('palm', 'nut'): 3,
         ('oil', 'and'): 3,
         ('off', 'a'): 3,
         ('piece', 'of'): 3,
         ('colors', 'of'): 3,
         ('the', 'local'): 3,
         ('over', 'charcoal,'): 3,
         ('that', 'promised'): 3,
         ('was', 'the'): 3,
         ('the', 'chicken'): 3,
         ('lemon', 'juice,'): 3,
         ('was', 'both'): 3,
         ('grilled', 'over'): 3,
         ('and', 'her'): 3,
         ('with', 'fresh'): 3,
         ('heat', 'and'): 3,
         ('the', 'warmth'): 3,
         ('warmth', 'of'): 3,
         ('tomato', 'sauce'): 3,
         ('of', 'both'): 3,
         ('and', 'shared'): 3,
         ('Doro', 'Wat,'): 3,
         ('and', 'spicy'): 3,
         ('the', 'air,'): 3,
         ('grilled', 'fish'): 3,
         ('fish', 'and'): 3,
         ('side', 'dish'): 3,
         ('of', 'community'): 3,
         ('air', 'as'): 3,
         ('of', 'Kenyan'): 3,
         ('life', '-'): 3,
         ('hearty', 'stew'): 3,
         ('body', 'and'): 3,
         ('and', 'spices,'): 3,
         ('meal', 'that'): 3,
         ('city', 'of'): 3,
         ('in', 'banana'): 3,
         ('and', 'flavorful'): 3,
         ('essential', 'nutrients'): 3,
         ('a', 'height'): 3,
         ('height', 'of'): 3,
         ('thousands', 'of'): 3,
         ('of', 'ecological'): 3,
         ('sense', 'of'): 3,
         ("world's", 'largest'): 3,
         ('teeming', 'with'): 3,
         ('Visitors', 'can'): 3,
         ('beauty', 'of'): 3,
         ('Egypt', 'and'): 3,
         ('among', 'the'): 3,
         ('the', 'oldest'): 3,
         ('the', 'ancient'): 3,
         ('insights', 'into'): 3,
         ('the', 'world,'): 3,
         ('destination', 'for'): 3,
         ('Park,', 'located'): 3,
         ('balance', 'of'): 3,
         ('Heritage', 'Site,'): 3,
         ('history', 'and'): 3,
         ('their', 'laughter'): 3,
         ('their', 'voices'): 3,
         ('presence', 'in'): 3,
         ('was', 'being'): 3,
         ('moved', 'at'): 3,
         ('The', 'warm,'): 3,
         ('the', 'villagers,'): 3,
         ('villagers,', 'who'): 3,
         ('who', 'lived'): 3,
         ('the', 'water'): 3,
         ('of', 'West'): 3,
         ('guided', 'by'): 3,
         ('are', 'characterized'): 3,
         ('the', 'cultural'): 3,
         ('Central', 'Africa,'): 3,
         ('Africa,', 'and'): 3,
         ('Africa.', 'The'): 3,
         ('in', 'parts'): 3,
         ('considered', 'a'): 3,
         ('southern', 'Africa,'): 3,
         ('and', 'then'): 3,
         ('of', 'human'): 3,
         ('sign', 'languages'): 3,
         ('the', 'continent.'): 3,
         ('often', 'depicting'): 3,
         ('artists', 'are'): 3,
         ('sculptures', 'are'): 3,
         ('is', 'renowned'): 3,
         ('that', 'are'): 3,

In [27]:
print("Most common bigrams:")
for bigram, count in bigram_counts.most_common(10):
    print(f"{bigram}:\t{count}")

Most common bigrams:
('is', 'a'):	144
('of', 'the'):	100
('and', 'the'):	69
('in', 'the'):	61
('with', 'a'):	60
('in', 'a'):	55
('and', 'a'):	50
('to', 'the'):	42
('was', 'a'):	39
('It', 'is'):	33

In [28]:
trigram_counts = Counter(all_trigrams)
trigram_counts

Counter({('went', 'looking', 'for'): 32,
         ('a', 'symbol', 'of'): 18,
         ('was', 'hungry', 'so'): 18,
         ('The', 'result', 'is'): 17,
         ('looking', 'for', 'a'): 17,
         ('she', 'went', 'looking'): 16,
         ('he', 'went', 'looking'): 16,
         ('result', 'is', 'a'): 15,
         ('so', 'he', 'went'): 14,
         ('so', 'she', 'went'): 14,
         ('is', 'a', 'traditional'): 14,
         ('one', 'of', 'the'): 13,
         ('more', 'than', 'just'): 12,
         ('was', 'more', 'than'): 11,
         ('it', 'was', 'a'): 11,
         ('a', 'testament', 'to'): 11,
         ('hungry', 'so', 'he'): 11,
         ('making', 'it', 'a'): 10,
         ('was', 'thirsty', 'so'): 10,
         ('a', 'taste', 'of'): 9,
         ('is', 'a', 'popular'): 9,
         ('It', 'is', 'made'): 9,
         ('is', 'made', 'by'): 9,
         ('is', 'a', 'staple'): 9,
         ('testament', 'to', 'the'): 8,
         ('UNESCO', 'World', 'Heritage'): 8,
         ('was', 'a', 'symbol'): 7,
         ('hungry', 'so', 'she'): 7,
         ('thirsty', 'so', 'she'): 7,
         ('a', 'reminder', 'of'): 6,
         ('is', 'characterized', 'by'): 6,
         ('a', 'variety', 'of'): 6,
         ('to', 'scoop', 'up'): 6,
         ('to', 'create', 'a'): 6,
         ('a', 'staple', 'in'): 6,
         ('It', 'was', 'a'): 6,
         ('a', 'UNESCO', 'World'): 6,
         ('a', 'place', 'where'): 6,
         ('is', 'one', 'of'): 6,
         ('cooked', 'in', 'a'): 6,
         ('giving', 'it', 'a'): 6,
         ('often', 'served', 'with'): 6,
         ('spices', 'such', 'as'): 6,
         ('filled', 'with', 'the'): 5,
         ('than', 'just', 'a'): 5,
         ('resulting', 'in', 'a'): 5,
         ('a', 'burst', 'of'): 5,
         ('than', 'just', 'food;'): 5,
         ('just', 'food;', 'it'): 5,
         ('food;', 'it', 'was'): 5,
         ('scoop', 'up', 'the'): 5,
         ('served', 'with', 'a'): 5,
         ('dish', 'made', 'from'): 5,
         ('made', 'from', 'fermented'): 5,
         ('the', 'scent', 'of'): 5,
         ('renowned', 'for', 'its'): 5,
         ('can', 'be', 'a'): 5,
         ('is', 'often', 'served'): 5,
         ('It', 'has', 'a'): 5,
         ('is', 'typically', 'served'): 5,
         ('Africa.', 'It', 'is'): 5,
         ('served', 'in', 'a'): 5,
         ('a', 'celebration', 'of'): 4,
         ('was', 'filled', 'with'): 4,
         ('a', 'source', 'of'): 4,
         ('a', 'woman', 'with'): 4,
         ('the', 'rich', 'cultural'): 4,
         ('the', 'heart', 'of'): 4,
         ('In', 'a', 'small'): 4,
         ('characterized', 'by', 'its'): 4,
         ('is', 'a', 'testament'): 4,
         ('serving', 'as', 'a'): 4,
         ('to', 'the', 'power'): 4,
         ('the', 'power', 'of'): 4,
         ('also', 'known', 'as'): 4,
         ('is', 'a', 'beloved'): 4,
         ('characterized', 'by', 'a'): 4,
         ('are', 'known', 'for'): 4,
         ('known', 'for', 'its'): 4,
         ('lived', 'in', 'a'): 4,
         ('the', 'air', 'was'): 4,
         ('with', 'a', 'slightly'): 4,
         ('filled', 'with', 'a'): 4,
         ('on', 'the', 'outside'): 4,
         ('the', 'outside', 'and'): 4,
         ('taste', 'of', 'home,'): 4,
         ('the', 'aroma', 'of'): 4,
         ('a', 'mixture', 'of'): 4,
         ('in', 'a', 'rich'): 4,
         ('rhythmic', 'beat', 'of'): 4,
         ('served', 'with', 'grilled'): 4,
         ('and', 'a', 'taste'): 4,
         ('largest', 'and', 'most'): 4,
         ('beliefs', 'of', 'the'): 4,
         ('World', 'Heritage', 'Site'): 4,
         ('of', 'the', 'most'): 4,
         ('language', 'family', 'is'): 4,
         ('of', 'the', 'largest'): 4,
         ('in', 'the', 'world.'): 4,
         ('and', 'parts', 'of'): 4,
         ('health', 'and', 'well-being.'): 4,
         ('looking', 'for', 'the'): 4,
         ('color', 'and', 'a'): 4,
         ('a', 'plate', 'of'): 4,
         ('a', 'cup', 'of'): 4,
         ('a', 'traditional', 'South'): 4,
         ('traditional', 'South', 'African'): 4,
         ('a', 'street', 'vendor'): 4,
         ('flavor', 'and', 'a'): 4,
         ('enjoyed', 'as', 'a'): 4,
         ('is', 'made', 'from'): 4,
         ('with', 'spices', 'such'): 4,
         ('made', 'from', 'the'): 4,
         ('of', 'energy', 'and'): 3,
         ('The', 'music', 'was'): 3,
         ('a', 'vibrant', 'expression'): 3,
         ('vibrant', 'expression', 'of'): 3,
         ('a', 'man', 'with'): 3,
         ('lost', 'in', 'the'): 3,
         ('alive', 'with', 'the'): 3,
         ('with', 'the', 'sounds'): 3,
         ('the', 'sounds', 'of'): 3,
         ('woman', 'with', 'a'): 3,
         ('reminder', 'of', 'the'): 3,
         ('was', 'alive', 'with'): 3,
         ('a', 'group', 'of'): 3,
         ('is', 'a', 'vibrant'): 3,
         ('a', 'wide', 'range'): 3,
         ('wide', 'range', 'of'): 3,
         ('and', 'South', 'Africa.'): 3,
         ('a', 'unique', 'and'): 3,
         ('distinct', 'wet', 'and'): 3,
         ('wet', 'and', 'dry'): 3,
         ('known', 'for', 'their'): 3,
         ('plant', 'and', 'animal'): 3,
         ('part', 'of', 'the'): 3,
         ('a', 'small', 'village'): 3,
         ('a', 'secret', 'blend'): 3,
         ('secret', 'blend', 'of'): 3,
         ('passed', 'down', 'through'): 3,
         ('burst', 'of', 'flavor'): 3,
         ('family,', 'and', 'the'): 3,
         ('a', 'boy', 'with'): 3,
         ('boy', 'with', 'a'): 3,
         ('to', 'tear', 'off'): 3,
         ('was', 'a', 'symphony'): 3,
         ('a', 'symphony', 'of'): 3,
         ('a', 'girl', 'with'): 3,
         ('The', 'air', 'was'): 3,
         ('onions,', 'garlic,', 'and'): 3,
         ('sun', 'beat', 'down'): 3,
         ('a', 'South', 'African'): 3,
         ('a', 'hint', 'of'): 3,
         ('casting', 'long', 'shadows'): 3,
         ('the', 'vibrant', 'colors'): 3,
         ('vibrant', 'colors', 'of'): 3,
         ('lemon', 'juice,', 'and'): 3,
         ('the', 'warmth', 'of'): 3,
         ('the', 'rhythmic', 'beat'): 3,
         ('at', 'a', 'small'): 3,
         ('filled', 'the', 'air'): 3,
         ('the', 'air', 'as'): 3,
         ('portion', 'of', 'the'): 3,
         ('of', 'the', "world's"): 3,
         ('the', "world's", 'largest'): 3,
         ('insights', 'into', 'the'): 3,
         ('in', 'the', 'world,'): 3,
         ('for', 'its', 'unique'): 3,
         ('National', 'Park,', 'located'): 3,
         ('is', 'a', 'vast'): 3,
         ('a', 'vital', 'role'): 3,
         ('vital', 'role', 'in'): 3,
         ('World', 'Heritage', 'Site,'): 3,
         ('with', 'the', 'scent'): 3,
         ('and', 'the', 'air'): 3,
         ('air', 'was', 'filled'): 3,
         ('moved', 'at', 'a'): 3,
         ('the', 'villagers,', 'who'): 3,
         ('villagers,', 'who', 'lived'): 3,
         ('guided', 'by', 'the'): 3,
         ('are', 'characterized', 'by'): 3,
         ('parts', 'of', 'East'): 3,
         ('in', 'parts', 'of'): 3,
         ('is', 'renowned', 'for'): 3,
         ('are', 'crucial', 'for'): 3,
         ('vitamins,', 'minerals,', 'and'): 3,
         ('is', 'essential', 'for'): 3,
         ('a', 'delicious', 'and'): 3,
         ('on', 'a', 'hot'): 3,
         ('and', 'can', 'be'): 3,
         ('water', 'is', 'a'): 3,
         ('slightly', 'sweet', 'and'): 3,
         ('a', 'touch', 'of'): 3,
         ('tomato', 'and', 'pepper'): 3,
         ('taste.', 'It', 'is'): 3,
         ('It', 'is', 'often'): 3,
         ('soup', 'is', 'a'): 3,
         ('is', 'a', 'hearty'): 3,
         ('typically', 'served', 'with'): 3,
         ('marinated', 'in', 'a'): 3,
         ('a', 'hearty', 'and'): 3,
         ('drawn', 'by', 'the'): 3,
         ('for', 'a', 'plate'): 3,
         ('at', 'a', 'local'): 3,
         ('the', 'enticing', 'aroma'): 3,
         ('enticing', 'aroma', 'of'): 3,
         ('paired', 'with', 'a'): 3,
         ('at', 'a', 'bustling'): 3,
         ('thirsty', 'so', 'he'): 3,
         ('a', 'traditional', 'Ethiopian'): 3,
         ('led', 'him', 'to'): 3,
         ('him', 'to', 'a'): 3,
         ('a', 'glass', 'of'): 3,
         ('slightly', 'tangy', 'flavor'): 3,
         ('a', 'long', 'day'): 3,
         ('a', 'slightly', 'sour'): 3,
         ('The', 'stew', 'is'): 3,
         ('popular', 'in', 'West'): 3,
         ('often', 'enjoyed', 'as'): 3,
         ('is', 'seasoned', 'with'): 3,
         ('African', 'fried', 'dough'): 3,
         ('that', 'is', 'a'): 3,
         ('Kenya', 'and', 'Tanzania.'): 3,
         ('is', 'usually', 'served'): 3,
         ('and', 'is', 'a'): 3,
         ('is', 'often', 'enjoyed'): 3,
         ('is', 'a', 'spicy'): 3,
         ('is', 'used', 'to'): 3,
         ('and', 'Tanzania.', 'The'): 3,
         ('is', 'cooked', 'with'): 3,
         ('such', 'as', 'cumin,'): 3,
         ('Africa', 'made', 'from'): 3,
         ('It', 'is', 'a'): 3,
         ('a', 'bit', 'of'): 3,
         ('seasoned', 'with', 'spices'): 3,
         ('in', 'countries', 'like'): 3,
         ('African', 'countries', 'like'): 3,
         ('served', 'as', 'a'): 3,
         ('with', 'water', 'and'): 3,
         ('with', 'spices', 'like'): 3,
         ('from', 'South', 'Africa,'): 3,
         ('allowing', 'it', 'to'): 3,
         ('is', 'rich', 'in'): 3,
         ('drink', 'made', 'from'): 3,
         ('beverage', 'with', 'a'): 3,
         ('The', 'drink', 'is'): 3,
         ('is', 'both', 'refreshing'): 3,
         ('both', 'refreshing', 'and'): 3,
         ('typically', 'served', 'in'): 3,
         ('on', 'the', 'African'): 3,
         ('vast', 'herds', 'of'): 3,
         ('National', 'Park', 'is'): 3,
         ('The', 'park', 'is'): 3,
         ('the', 'endangered', 'African'): 3,
         ('renowned', 'for', 'their'): 3,
         ('is', 'a', 'large'): 3,
         ('is', 'the', "world's"): 3,
         ('on', 'leaves', 'and'): 3,
         ('is', 'a', 'large,'): 3,
         ('air', 'was', 'thick'): 2,
         ('was', 'thick', 'with'): 2,
         ('to', 'the', 'music,'): 2,
         ('rhythm.', 'The', 'music'): 2,
         ('of', 'life,', 'a'): 2,
         ('a', 'connection', 'to'): 2,
         ('At', 'a', 'small'): 2,
         ('tucked', 'away', 'on'): 2,
         ('away', 'on', 'a'): 2,
         ('band', 'played,', 'the'): 2,
         ('played,', 'the', 'guitars'): 2,
         ('the', 'guitars', 'weaving'): 2,
         ('guitars', 'weaving', 'intricate'): 2,
         ('in', 'the', 'music.'): 2,
         ('the', 'music.', 'The'): 2,
         ('music', 'was', 'a'): 2,
         ('feet', 'to', 'the'): 2,
         ('was', 'a', 'constant'): 2,
         ('with', 'activity', 'as'): 2,
         ('activity', 'as', 'the'): 2,
         ('as', 'the', 'sun'): 2,
         ('the', 'sun', 'began'): 2,
         ('sun', 'began', 'to'): 2,
         ('began', 'to', 'set.'): 2,
         ('a', 'blend', 'of'): 2,
         ('and', 'joy,', 'a'): 2,
         ('night', 'was', 'alive'): 2,
         ('of', 'life', 'and'): 2,
         ('in', 'the', 'heart'): 2,
         ('group', 'of', 'men'): 2,
         ('of', 'men', 'gathered'): 2,
         ('a', 'way', 'to'): 2,
         ('tell', 'stories', 'of'): 2,
         ('Kente', 'is', 'a'): 2,
         ('and', 'artistry.', 'The'): 2,
         ('the', 'spirit', 'of'): 2,
         ('from', 'Mali,', 'is'): 2,
         ('patterns,', 'created', 'using'): 2,
         ('has', 'become', 'a'): 2,
         ('become', 'a', 'symbol'): 2,
         ('and', 'a', 'testament'): 2,
         ('from', 'Nigeria,', 'is'): 2,
         ('East', 'Africa,', 'particularly'): 2,
         ('a', 'vibrant', 'and'): 2,
         ('Africa', 'and', 'beyond.'): 2,
         ('in', 'Southern', 'Africa,'): 2,
         ('Africa,', 'particularly', 'in'): 2,
         ('it', 'a', 'popular'): 2,
         ('with', 'some', 'areas'): 2,
         ('a', 'tropical', 'rainforest'): 2,
         ('tropical', 'rainforest', 'climate,'): 2,
         ('climate,', 'characterized', 'by'): 2,
         ('the', 'year.', 'The'): 2,
         ('high', 'humidity', 'and'): 2,
         ('vary', 'depending', 'on'): 2,
         ('the', 'combination', 'of'): 2,
         ('of', 'plant', 'and'): 2,
         ('and', 'animal', 'species.'): 2,
         ('The', 'Mediterranean', 'coast'): 2,
         ('with', 'warm', 'summers'): 2,
         ('warm', 'summers', 'and'): 2,
         ('of', 'fruits,', 'vegetables,'): 2,
         ('diverse', 'range', 'of'): 2,
         ('The', 'western', 'coast'): 2,
         ('western', 'coast', 'is'): 2,
         ('coast', 'is', 'characterized'): 2,
         ('on', 'Earth.', 'The'): 2,
         ('have', 'a', 'more'): 2,
         ('a', 'more', 'temperate'): 2,
         ('more', 'temperate', 'climate,'): 2,
         ('temperate', 'climate,', 'with'): 2,
         ('The', 'eastern', 'coast'): 2,
         ('eastern', 'coast', 'is'): 2,
         ('by', 'the', 'warm'): 2,
         ('an', 'island', 'nation'): 2,
         ('island', 'nation', 'off'): 2,
         ('coast', 'of', 'Africa,'): 2,
         ('due', 'to', 'its'): 2,
         ('climate', 'in', 'some'): 2,
         ('in', 'a', 'small'): 2,
         ('small', 'village', 'nestled'): 2,
         ('hummed', 'with', 'the'): 2,
         ('Mama', 'Ada', 'would'): 2,
         ('would', 'start', 'by'): 2,
         ('and', 'a', 'secret'): 2,
         ('blend', 'of', 'spices'): 2,
         ('The', 'vibrant', 'red'): 2,
         ('with', 'each', 'passing'): 2,
         ('each', 'passing', 'moment.'): 2,
         ('The', 'stories,', 'like'): 2,
         ('stories,', 'like', 'the'): 2,
         ('her', 'heritage.', 'When'): 2,
         ('heritage.', 'When', 'the'): 2,
         ('the', 'rice', 'was'): 2,
         ('would', 'serve', 'it'): 2,
         ('serve', 'it', 'on'): 2,
         ('of', 'the', 'fire'): 2,
         ('the', 'fire', 'and'): 2,
         ('fire', 'and', 'the'): 2,
         ('and', 'the', 'vibrant'): 2,
         ('Each', 'mouthful', 'was'): 2,
         ('mouthful', 'was', 'a'): 2,
         ('was', 'a', 'burst'): 2,
         ('and', 'the', 'rich'): 2,
         ('Alem,', 'a', 'boy'): 2,
         ('with', 'a', 'mischievous'): 2,
         ('high', 'in', 'the'): 2,
         ('in', 'the', 'Ethiopian'): 2,
         ('helping', 'his', 'mother,'): 2,
         ('the', 'base', 'of'): 2,
         ('Mama', 'Selamawit', 'would'): 2,
         ('would', 'begin', 'by'): 2,
         ('ferment', 'for', 'several'): 2,
         ('The', 'air', 'would'): 2,
         ('air', 'would', 'fill'): 2,
         ('would', 'fill', 'with'): 2,
         ('it', 'on', 'a'): 2,
         ('on', 'a', 'platter,'): 2,
         ('loved', 'to', 'tear'): 2,
         ('tear', 'off', 'pieces'): 2,
         ('off', 'pieces', 'of'): 2,
         ('pieces', 'of', 'the'): 2,
         ('Each', 'bite', 'was'): 2,
         ('bite', 'was', 'a'): 2,
         ('symphony', 'of', 'flavors'): 2,
         ('the', 'soft,', 'slightly'): 2,
         ('to', 'the', 'land'): 2,
         ('the', 'land', 'and'): 2,
         ('eyes', 'and', 'a'): 2,
         ('stew', 'named', 'after'): 2,
         ('named', 'after', 'the'): 2,
         ('pot', 'in', 'which'): 2,
         ('garlic,', 'and', 'a'): 2,
         ('into', 'the', 'flavorful'): 2,
         ('just', 'a', 'meal;'): 2,
         ('a', 'meal;', 'it'): 2,
         ('meal;', 'it', 'was'): 2,
         ('cultural', 'heritage', 'of'): 2,
         ('beat', 'down', 'warmly'): 2,
         ('down', 'warmly', 'on'): 2,
         ('the', 'dusty', 'road'): 2,
         ('and', 'a', 'hint'): 2,
         ('long', 'shadows', 'across'): 2,
         ('shadows', 'across', 'the'): 2,
         ('Pap', 'en', 'Vleis'): 2,
         ('en', 'Vleis', 'was'): 2,
         ('meat,', 'charred', 'on'): 2,
         ('charred', 'on', 'the'): 2,
         ('outside', 'and', 'juicy'): 2,
         ('and', 'juicy', 'within,'): 2,
         ('juicy', 'within,', 'was'): 2,
         ('of', 'the', 'braai.'): 2,
         ('of', 'South', 'African'): 2,
         ('was', 'a', 'taste'): 2,
         ('of', 'home,', 'a'): 2,
         ('home,', 'a', 'symbol'): 2,
         ('under', 'the', 'African'): 2,
         ('girl', 'with', 'a'): 2,
         ('energy', 'and', 'a'): 2,
         ('in', 'the', 'afternoon'): 2,
         ('the', 'afternoon', 'sun.'): 2,
         ('air', 'filled', 'with'): 2,
         ('tear', 'off', 'a'): 2,
         ('off', 'a', 'piece'): 2,
         ('a', 'piece', 'of'): 2,
         ('a', 'dish', 'that'): 2,
         ('and', 'a', 'love'): 2,
         ('a', 'love', 'for'): 2,
         ('colors', 'of', 'the'): 2,
         ('of', 'Piri-Piri,', 'a'): 2,
         ('garlic,', 'lemon', 'juice,'): 2,
         ('blend', 'of', 'spices,'): 2,
         ('that', 'was', 'both'): 2,
         ('land', 'and', 'sea.'): 2,
         ('in', 'a', 'mixture'): 2,
         ('a', 'rich', 'tomato'): 2,
         ('aroma', 'of', 'simmering'): 2,
         ('sauce,', 'and', 'the'): 2,
         ('a', 'comforting', 'reminder'): 2,
         ('comforting', 'reminder', 'of'): 2,
         ('the', 'clinking', 'of'): 2,
         ('of', 'their', 'shared'): 2,
         ('and', 'their', 'bond'): 2,
         ('their', 'bond', 'as'): 2,
         ('bond', 'as', 'friends'): 2,
         ('as', 'friends', 'in'): 2,
         ('friends', 'in', 'this'): 2,
         ('in', 'this', 'vibrant'): 2,
         ('this', 'vibrant', 'city.'): 2,
         ('Bunny', 'Chow,', 'a'): 2,
         ('the', 'hurried', 'footsteps'): 2,
         ('hurried', 'footsteps', 'of'): 2,
         ('and', 'the', 'rhythmic'): 2,
         ('by', 'a', 'street'): 2,
         ('grilled', 'fish', 'and'): 2,
         ('side', 'dish', 'made'): 2,
         ('and', 'slightly', 'tangy,'): 2,
         ('with', 'grilled', 'fish'): 2,
         ('As', 'they', 'ate,'): 2,
         ('symbol', 'of', 'community'): 2,
         ('of', 'community', 'and'): 2,
         ('gathered', 'around', 'a'): 2,
         ('shared', 'stories', 'and'): 2,
         ('stories', 'and', 'laughter,'): 2,
         ('and', 'laughter,', 'the'): 2,
         ('food', 'stall,', 'a'): 2,
         ('stall,', 'a', 'woman'): 2,
         ('sweet', 'and', 'spicy'): 2,
         ('People', 'from', 'all'): 2,
         ('from', 'all', 'walks'): 2,
         ('all', 'walks', 'of'): 2,
         ('walks', 'of', 'life'): 2,
         ('of', 'life', '-'): 2,
         ('life', '-', 'students,'): 2,
         ('-', 'students,', 'traders,'): 2,
         ('students,', 'traders,', 'office'): 2,
         ('traders,', 'office', 'workers'): 2,
         ('office', 'workers', '-'): 2,
         ('workers', '-', 'stopped'): 2,
         ('a', 'portion', 'of'): 2,
         ('with', 'a', 'hearty'): 2,
         ('meat', 'and', 'vegetables'): 2,
         ('a', 'comforting', 'and'): 2,
         ('air', 'as', 'the'): 2,
         ('Moin', 'Moin,', 'a'): 2,
         ('and', 'flavorful', 'way'): 2,
         ('flavorful', 'way', 'to'): 2,
         ('the', 'East', 'African'): 2,
         ('a', 'height', 'of'): 2,
         ('at', 'its', 'base'): 2,
         ('its', 'base', 'to'): 2,
         ('panoramic', 'views', 'of'): 2,
         ('views', 'of', 'the'): 2,
         ('a', 'sense', 'of'): 2,
         ('a', 'lush', 'oasis'): 2,
         ('flora', 'and', 'fauna.'): 2,
         ('Visitors', 'can', 'experience'): 2,
         ('offering', 'a', 'unique'): 2,
         ('the', 'power', 'and'): 2,
         ('located', 'on', 'the'): 2,
         ('the', 'oldest', 'and'): 2,
         ('oldest', 'and', 'most'): 2,
         ('and', 'one', 'of'): 2,
         ('the', 'mysteries', 'of'): 2,
         ('recognized', 'for', 'its'): 2,
         ('animal', 'species,', 'making'): 2,
         ('species,', 'making', 'it'): 2,
         ('Park,', 'located', 'in'): 2,
         ('The', "park's", 'diverse'): 2,
         ('a', 'vast', 'array'): 2,
         ('vast', 'array', 'of'): 2,
         ('plays', 'a', 'vital'): 2,
         ('it', 'offers', 'a'): 2,
         ('sights,', 'sounds,', 'and'): 2,
         ('is', 'a', 'customary'): 2,
         ('rich', 'history', 'and'): 2,
         ('history', 'and', 'cultural'): 2,
         ('thick', 'with', 'the'): 2,
         ('Sunlight', 'streamed', 'through'): 2,
         ('streamed', 'through', 'the'): 2,

In [29]:
print("\n\nMost common trigrams:")
for trigram, count in trigram_counts.most_common(10):
    print(f"{trigram}:\t{count}")

Most common trigrams:
('went', 'looking', 'for'):	32
('a', 'symbol', 'of'):	18
('was', 'hungry', 'so'):	18
('The', 'result', 'is'):	17
('looking', 'for', 'a'):	17
('she', 'went', 'looking'):	16
('he', 'went', 'looking'):	16
('result', 'is', 'a'):	15
('so', 'he', 'went'):	14
('so', 'she', 'went'):	14

In [30]:
def get_ngram_counts(dataset: list[str], n: int) -> dict[str, Counter]:
    """Computes the n-gram counts from a dataset.

    This function takes a list of text strings (paragraphs or sentences) as
    input, constructs n-grams from each text, and creates a dictionary where:

    * Keys represent n-1 token long contexts `context`.
    * Values are a Counter object `counts` such that `counts[next_token]` is the
      count of `next_token` following `context`.

    Args:
        dataset: The list of text strings in the dataset.
        n: The size of the n-grams to generate (e.g., 2 for bigrams, 3 for
            trigrams).

    Returns:
        A dictionary where keys are (n-1)-token contexts and values are Counter
        objects storing the counts of each next token for that context.

    """

    # Define the dictionary as a defaultdict that is automatically initialized
    # with an empty Counter object. This allows you to access and set the value
    # of ngram_counts[context][next_token] without initializing
    # ngram_counts[context] or ngram_counts[context][next_token] first.
    # Reference
    # https://docs.python.org/3/library/collections.html#collections.Counter and
    # https://docs.python.org/3/library/collections.html#collections.defaultdict
    # for more information on how to use defaultdict and Counter types.
    ngram_counts = defaultdict(Counter)

    for paragraph in dataset:
        ngrams = generate_ngrams(text=paragraph, n=n)
        for ngram in ngrams:
            context = " ".join(ngram[:-1])
            next_token = ngram[-1]
            ngram_counts[context][next_token] += 1

    return dict(ngram_counts)


# Example usage of the function.
example_data = [
    "This is an example sentence.",
    "Another example sentence.",
    "Split a sentence."
]
ngram_counts = get_ngram_counts(example_data, 2)

# Print the bigram counts dictionary for the dataset consisting of the
# three example sentences.
print("Bigram counts dictionary:\n")
print("{")
for context, counter in ngram_counts.items():
    print(f"  '{context}': {counter},")
print("}")

Bigram counts dictionary:

{
  'This': Counter({'is': 1}),
  'is': Counter({'an': 1}),
  'an': Counter({'example': 1}),
  'example': Counter({'sentence.': 2}),
  'Another': Counter({'example': 1}),
  'Split': Counter({'a': 1}),
  'a': Counter({'sentence.': 1}),
}

In [31]:
bigram_counts = get_ngram_counts(dataset, n=2)

# Use the pandas library to display the counts in a table.
bigram_counts_matrix = {
    context: dict(counts) for context, counts in bigram_counts.items()
}
bigram_data_frame = pd.DataFrame.from_dict(
    bigram_counts_matrix, orient="index").fillna(0)

display(bigram_data_frame)

,Lagos,band,music,warm,Highlife,bustling,Dakar,Mbalax,Kinshasa,Soukous,...,"kudu,","mph),",Ostriches,Antarctic,plumage,surface.,(Spheniscus,demersus).,breed,Bay
The,1.0,1.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
of,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
the,0.0,1.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
a,0.0,1.0,0.0,6.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
with,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
water's,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Penguin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
(Spheniscus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
penguins,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Algoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [32]:
zero_count = (bigram_data_frame == 0).sum().sum()
print(
    f"Number of bigrams with a count of 0: {zero_count:,}"
    f" ({zero_count/bigram_data_frame.size * 100:.2f}%)"
)

Number of bigrams with a count of 0: 26,606,550 (99.95%)

In [33]:
trigram_counts = get_ngram_counts(dataset, n=3)

# Use the pandas library to display the counts in a table.
trigram_counts_matrix = {
    context: dict(counts) for context, counts in trigram_counts.items()
}
trigram_data_frame = pd.DataFrame.from_dict(
    trigram_counts_matrix, orient="index").fillna(0)

display(trigram_data_frame)

,air,was,thick,thin,always,"quiet,",filled,alive,with,"humidity,",...,plumage,water's,surface.,penguin,(Spheniscus,demersus).,penguins,breed,Algoa,Bay
The Lagos,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
in the,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
and the,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
warm evening,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
vegetables. The,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Penguin (Spheniscus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
demersus). These,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
These penguins,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
down to,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
to Algoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [34]:
zero_count = (trigram_data_frame == 0).sum().sum()
print(
    f"Number of trigrams with a count of 0: {zero_count:,}"
    f" ({zero_count/trigram_data_frame.size * 100:.2f}%)"
)

Number of trigrams with a count of 0: 68,942,324 (99.98%)

In [35]:
# Counts for the numerator.
trigram_counts = get_ngram_counts(dataset, n=3)
# Counts for the denominator.
bigram_counts = get_ngram_counts(dataset, n=2)

In [36]:
context = "a staple"
trigram_counts[context]

Counter({'in': 6,
         'dish': 2,
         'food': 1,
         'throughout': 1,
         'of': 1,
         'at': 1,
         'beverage': 1})

In [37]:
context = "a staple"
# Compute the bigram count for "a staple" with sum().
bigram_count_a_staple = sum(trigram_counts[context].values())

In [38]:
print(
    'Bigram count of "a staple" computed indirectly from trigram counts: ',
    bigram_count_a_staple,
)

Bigram count of "a staple" computed indirectly from trigram counts:  13

In [39]:
# Extract the bigram count for "a staple" from bigram_counts.
print('Bigram count of "a staple" computed directly: ',
      bigram_counts["a"]["staple"])

Bigram count of "a staple" computed directly:  13

In [40]:
def build_ngram_model(
    dataset: list[str],
    n: int
) -> dict[str, dict[str, float]]:
    """Builds an n-gram language model.

    This function takes a list of text strings (paragraphs or sentences) as
    input, generates n-grams from each text using the function get_ngram_counts
    and converts them into probabilities.  The resulting model is a dictionary,
    where keys are (n-1)-token contexts and values are dictionaries mapping
    possible next tokens to their conditional probabilities given the context.

    Args:
        dataset: A list of text strings representing the dataset.
        n: The size of the n-grams (e.g., 2 for a bigram model).

    Returns:
        A dictionary representing the n-gram language model, where keys are
        (n-1)-tokens contexts and values are dictionaries mapping possible next
        tokens to their conditional probabilities.
    """

    # A dictionary to store P(B | A).
    # ngram_model[context][token] should store P(token | context).
    ngram_model = {}

    # Use the ngram_counts as computed by the get_ngram_counts function.
    ngram_counts = get_ngram_counts(dataset, n)

    # Loop through the possible contexts. `context` is a string
    # and `next_tokens` is a dictionary mapping possible next tokens to their
    # counts of following `context`.
    for context, next_tokens in ngram_counts.items():
        total_count = sum(next_tokens.values())
        ngram_model[context] = {
            token: count / total_count for token, count in next_tokens.items()
        }

    return ngram_model

In [41]:
# Test the method above by bulding a simple trigram model.
test_dataset = ["Table Mountain is tall.", "Table Mountain is beautiful."]
test_trigram_model = build_ngram_model(test_dataset, n=3)
test_trigram_model

{'Table Mountain': {'is': 1.0},
 'Mountain is': {'tall.': 0.5, 'beautiful.': 0.5}}

In [42]:
trigram_model = build_ngram_model(dataset, n=3)

In [43]:
print(f"P(B | \"as it\") = {trigram_model['as it']}")

print(f"P(B | \"as they\") = {trigram_model['as they']}")

P(B | "as it") = {'is': 0.6666666666666666, 'receives': 0.3333333333333333}
P(B | "as they") = {'were': 1.0}

In [44]:
context = "The name"
trigram_model[context]

{'means': 0.6666666666666666, "'Etosha'": 0.3333333333333333}

In [46]:
context = "Their name"
trigram_model[context]

KeyError: 'Their name'

In [47]:
# Define a list of tokens.
example_candidate_tokens = ["apple", "banana", "cherry"]

# Define corresponding probabilities for each fruit.
probabilities = [0.2, 0.5, 0.3]

# Sample one fruit based on the probabilities.
# The 'k=1' parameter instructs the function to return one item.
chosen_fruit = random.choices(
    example_candidate_tokens,
    weights=probabilities,
    k=1)[0]

print("Chosen fruit:", chosen_fruit)

Chosen fruit: banana

In [48]:
context = "looking for"
candidate_tokens = []
candidate_tokens_probabilities = []

# Extract candidate tokens and associated probabilities from `trigram_model`.
# Add your code here.
candidate_tokens = list(trigram_model[context].keys())
candidate_tokens_probabilities = list(trigram_model[context].values())

print(f"Candidate tokens: {candidate_tokens}")
print(f"Candidate token probabilities: {candidate_tokens_probabilities}")

# Sample from the list of candidate tokens according to the
# associated probabilities.
next_token = random.choices(candidate_tokens,
                            weights=candidate_tokens_probabilities)[0]

print("\n\nSampled next token:")
print(context, next_token)

Candidate tokens: ['the', 'a', 'Banku', 'Tella,', 'Maafe,', 'Umqombothi,', 'sugarcane', 'crispy', 'warm', 'Doro', 'sambusa,', 'dodo,', 'Fura']
Candidate token probabilities: [0.125, 0.53125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125]


Sampled next token:
looking for Fura

In [49]:
def generate_next_n_tokens(
    n: int,
    ngram_model: dict[str, dict[str, float]],
    prompt: str,
    num_tokens_to_generate: int,
) -> str:
    """Generates `num_tokens_to_generate` tokens following a given prompt using
    an n-gram language model.

    This function takes an n-gram model and uses it to predict the most
    likely next token for the given prompt. The generation process
    continues iteratively, appending predicted tokens to the prompt until the
    desired number of tokens is generated or a context is
    encountered for which the model has no predictions.

    Args:
        n: The size of the n-grams to use (e.g., 2 for a bigram model).
        ngram_model: A dictionary representing the n-gram language model.
        prompt: The starting text prompt for generating the next tokens.
        num_tokens_to_generate: The number of words to generate following
            the prompt.

    Returns:
        A string containing the original prompt followed by the generated
        tokens. If no valid continuation is found for a given context, the
        function will return the text generated up to that point and print a
        message indicating that no continuation could be found.
    """

    # Split prompt into individual tokens.
    generated_words = space_tokenize(prompt)

    for _ in range(num_tokens_to_generate):
        # Get last (n-1) tokens as context.
        context = generated_words[-(n - 1):]
        context = " ".join(context)
        if context in ngram_model:
            # Sample next word based on probabilities.
            next_word = random.choices(
                list(ngram_model[context].keys()),
                weights=ngram_model[context].values()
            )[0]

            generated_words.append(next_word)
        else:
            print(
                "⚠️ No valid continuation found. Change the prompt or"
                " try sampling another continuation.\n"
            )
            break

    return " ".join(generated_words)

In [50]:
prompt = "Jide was hungry so she went looking for"

# Construct a bigram model using the Africa Galore dataset.
bigram_model = build_ngram_model(dataset, n=2)

n = 2  # Bigram.
num_tokens_to_generate = 10  # Generate next n words.
generate_next_n_tokens(
    n=n,
    ngram_model=bigram_model,
    prompt=prompt,
    num_tokens_to_generate=num_tokens_to_generate,
)

⚠️ No valid continuation found. Change the prompt or try sampling another continuation.

'Jide was hungry so she went looking for their spiritual worldview.'

In [51]:
prompt = "Jide was hungry so she went looking for"

n = 3  # Trigram.
num_tokens_to_generate = 10  # Generate next n words.
generate_next_n_tokens(
    n=n,
    ngram_model=trigram_model,
    prompt=prompt,
    num_tokens_to_generate=num_tokens_to_generate,
)

'Jide was hungry so she went looking for dodo, the crispy skin crackling under her teeth, followed by'